# https://osbuild.org/docs/user-guide/blueprint-reference/

#
# Base definition
#
name = "base-image"
description = "RHEL Base Image"
version = "2025.05.15"
distro = "rhel-9"

#
# Boot parameters
#
[customizations.kernel]
append = "net.ifnames.prefix=net quiet"

#
# Partitions
#
[[customizations.disk.partitions]]
type = "plain"
label = "boot"
mountpoint = "/boot"
fs_type = "xfs"
minsize = "1 GiB"
[[customizations.disk.partitions]]
type = "lvm"
name = "vg_root"
minsize = "30 GiB"

[[customizations.disk.partitions.logical_volumes]]
name = "lv_root"
mountpoint = "/"
label = "root"
fs_type = "xfs"
minsize = "8 GiB"
[[customizations.disk.partitions.logical_volumes]]
name = "lv_home"
mountpoint = "/home"
label = "home"
fs_type = "xfs"
minsize = "2 GiB"
[[customizations.disk.partitions.logical_volumes]]
name = "lv_swap"
label = "swap"
fs_type = "swap"
minsize = "2 GiB"
[[customizations.disk.partitions.logical_volumes]]
name = "lv_tmp"
mountpoint = "/tmp"
label = "tmp"
fs_type = "xfs"
minsize = "2 GiB"
[[customizations.disk.partitions.logical_volumes]]
name = "lv_var"
mountpoint = "/var"
label = "var"
fs_type = "xfs"
minsize = "8 GiB"
[[customizations.disk.partitions.logical_volumes]]
name = "lv_var_log"
mountpoint = "/var/log"
label = "var_log"
fs_type = "xfs"
minsize = "2 GiB"
[[customizations.disk.partitions.logical_volumes]]
name = "lv_v_l_audit"
mountpoint = "/var/log/audit"
label = "v_l_audit"
fs_type = "xfs"
minsize = "2 GiB"
[[customizations.disk.partitions.logical_volumes]]
name = "lv_var_tmp"
mountpoint = "/var/tmp"
label = "var_tmp"
fs_type = "xfs"
minsize = "2 GiB"

#
# Time
#
[customizations.timezone]
timezone = "Europe/Helsinki"
ntpservers = ["time.cloudflare.com"]

#
# Locale
#
[customizations.locale]
languages = ["C.UTF-8"]
keyboard = "fi"

#
# Firewall
#
[customizations.firewall.services]
enabled = ["ssh"]

#
# Services
#
[customizations.services]
enabled = ["sshd", "tuned"]

#
# Packages
#
[[packages]]
name = "bash-completion"
[[packages]]
name = "bind-utils"
[[packages]]
name = "firewalld"
[[packages]]
name = "glibc-langpack-en"
[[packages]]
name = "glibc-minimal-langpack"
[[packages]]
name = "man-pages"
[[packages]]
name = "nano"
#[[packages]]
#name = "NetworkManager-config-server"
## https://bugzilla.redhat.com/show_bug.cgi?id=2041424
## https://issues.redhat.com/browse/RHELPLAN-108305
#[[packages]]
#name = "perl-File-Temp"
[[packages]]
name = "python3"
[[packages]]
name = "setools-console"
#[[packages]]
#name = "unzip"
#[[packages]]
#name = "vim-enhanced"
#[[packages]]
#name = "zstd"

#
# FIPS mode
#
#[customizations]
#fips = true

#
# Security compliance
#
# Run something like the following for the needed blueprint changes:
# oscap xccdf generate fix --fix-type blueprint --profile cis \
#   /usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml
#[customizations.openscap]
#datastream = "/usr/share/xml/scap/ssg/content/ssg-rhel9-ds.xml"
#profile_id = "xccdf_org.ssgproject.content_profile_cis"

#
# Root
#
[[customizations.user]]
name = "root"
key = "ssh-ed25519 changeme id_ed25519.pub"

#
# User
#
[[customizations.user]]
name = "admin"
description = "Admin User"
#password = "$6$..."
key = "ssh-ed25519 changeme id_ed25519.pub"
home = "/home/admin"
shell = "/bin/bash"
groups = ["wheel"]
uid = 4444

[[customizations.files]]
path = "/etc/sudoers.d/admin"
mode = "0440"
data = """
admin ALL=(ALL) NOPASSWD: ALL
"""
